ASSIGNMENT/VENKATESH/ASSIGNMENT 2 FLASK APPLICATION/web_app/app/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import Required

class SearchForm(Form):
    search_string = StringField('Enter search string')
    submit = SubmitField('Submit')

ASSIGNMENT/VENKATESH/ASSIGNMENT 2 FLASK APPLICATION/web_app/app/main/__init__.py
from flask import Blueprint
from .. import app

main = Blueprint( 'main', __name__, )

from . import views
from . import forms

app.register_blueprint(main)

ASSIGNMENT/VENKATESH/ASSIGNMENT 2 FLASK APPLICATION/web_app/app/main/views.py
try:
    import impyla 
except ImportError:
    print("Installing missing impyla")
    import pip
    pip.main(['install', '--no-deps', 'impyla'])

try:
    import thrift_sasl
except ImportError:
    print("Installing missing thrift_sasl")
    import pip
    # need a patched version of thrift_sasl.  see https://github.com/cloudera/impyla/issues/238
    pip.main(['install', '--no-deps', 'git+https://github.com/snowch/thrift_sasl'])



from flask import Flask, render_template, session, redirect, url_for, request, flash
from flask.ext.login import login_required, current_user
from . import forms
from . import main 
from .. import app
#from . import app

from ..models import Movie, Recommendation, Rating, User
from ..dao import RecommendationsNotGeneratedException, RecommendationsNotGeneratedForUserException

import flask
from bokeh.embed import components
from bokeh.plotting import figure
from bokeh.resources import INLINE
from bokeh.util.string import encode_utf8

from impala.dbapi import connect 
from impala.util import as_pandas
from .. import messagehub_client
import time
import json

@main.route('/', methods=['GET'])
def index():

    return render_template('/main/home.html', 
            movies = session.get('movies'))


@main.route('/recommendations', methods=['GET', 'POST'])
def recommendations():

    user_id = current_user.get_id()

    if not user_id:
        flash('Recommendations are only available if you have an account.') 
        return render_template('/main/recommendations.html', recommendations=[])

    else:
        rated_movies = Rating.get_ratings(current_user.get_id())

        # the user needs to have rated some movies to be able to receive recommendations
        if len(rated_movies.keys()) == 0 and current_user.get_id():
            flash('No Recommendations found, please rate some movies.') 
            return render_template('/main/recommendations.html', recommendations=[], timestamp=None)

        try:
            timestamp = Recommendation.get_latest_recommendation_timestamp()
            (recommendation_type, recommendations) = \
                    Recommendation.get_recommendations(current_user.get_id())

        except RecommendationsNotGeneratedException:
            flash('No recommendations available - the Recommendation process has not run yet.') 
            return render_template('/main/recommendations.html', recommendations=[])
        except RecommendationsNotGeneratedForUserException:
            flash('No Recommendations found, please rate some movies.') 
            return render_template('/main/recommendations.html', recommendations=[], timestamp=timestamp)

        if recommendation_type:
            flash("Recommendation type: " + recommendation_type)

        return render_template('/main/recommendations.html', recommendations=recommendations, timestamp=timestamp)

@main.route('/search', methods=['POST'])
def search():
    form = forms.SearchForm()
    session['search_string'] = form.search_string.data

    search_string = session.get('search_string') 
    if search_string:
        search_string = search_string.strip()
        session['movies'] = Movie.find_movies(
                                        current_user.get_id(),
                                        session.get('search_string')
                                        )
    else:
        session['movies'] = []

    return render_template('/main/search_results.html', 
            search_string = search_string,
            movies = session.get('movies'))

@main.route('/set_rating', methods=['POST'])
@login_required
def set_rating():

    if not request.json or \
       not 'movie_id' in request.json or \
       not 'user_id' in request.json or \
       not 'rating' in request.json:
        abort(400)

    movie_id = request.json['movie_id']
    user_id  = request.json['user_id']
    rating   = request.json['rating']

    if rating == '-':
        Rating.save_rating(movie_id, user_id, None)
    else:
        Rating.save_rating(movie_id, user_id, int(rating))

    return('{ "success": "true" }')

def get_hive_cursor():

    # TODO move Hive code to a new file hive_dao.py

    if not app.config['BI_HIVE_ENABLED']:
        return render_template('/main/bi_not_enabled.html')

    BI_HIVE_HOSTNAME = app.config['BI_HIVE_HOSTNAME']
    BI_HIVE_USERNAME = app.config['BI_HIVE_USERNAME']
    BI_HIVE_PASSWORD = app.config['BI_HIVE_PASSWORD']


    # TODO probably want to cache the connection rather than
    # instantiate it on every request
    
    # Note that BigInsights Enterprise clusters will need to specify the
    # ssl certificate because it is self-signed.

    try:
        conn = connect(
                    host=BI_HIVE_HOSTNAME,
                    port=10000, 
                    use_ssl=True, 
                    auth_mechanism='PLAIN', 
                    user=BI_HIVE_USERNAME, 
                    password=BI_HIVE_PASSWORD
                    )
    except:
        return None

    return conn.cursor()

@main.route("/report")
def report():

    cursor = get_hive_cursor()

    if cursor is None:
        return render_template('/main/bi_connection_issue.html')

    # FIXME we probably want to create aggregates on hadoop
    #       and cache them rather than returning the whole data
    #       set here

    # we need to ignore monitoring pings which have rating user_id = -1 
    # and movie_id = -1
    try:
        cursor.execute(
            "select * from movie_ratings where customer_id <> '-1' and movie_id <> '-1'", 
            configuration={ 
                'hive.mapred.supports.subdirectories': 'true', 
                'mapred.input.dir.recursive': 'true' 
                })
    except:
        return render_template('/main/bi_connection_issue.html')

    df = as_pandas(cursor)
    
    count = df.shape[0]

    if count == 0:
       return render_template('/main/bi_no_records.html')

    from bokeh.charts import Bar, output_file, show

    fig = Bar(
            df,
            label='movie_ratings.rating',
            values='movie_ratings.rating',
            agg='count',
            title='Distribution of movie ratings',
            legend=False
            )


    fig.plot_height = 400
    fig.xaxis.axis_label = 'Rating'
    fig.yaxis.axis_label = 'Count ( Rating )'

    js_resources = INLINE.render_js()
    css_resources = INLINE.render_css()

    script, div = components(fig)
    html = flask.render_template(
        '/main/embed.html',
        plot_script=script,
        plot_div=div,
        js_resources=js_resources,
        css_resources=css_resources,
    )
    return encode_utf8(html)

def check_auth(username, password):

    user = User.find_by_email(username)

    if user is not None and user.verify_password(password):
        return True
    else:
        return False

# This method keeps a thread open for a long time which is
# not ideal, but is the simplest way of checking.

@main.route("/monitor")
def monitor():

    auth = request.authorization
    if not auth or not check_auth(auth.username, auth.password):
        data = { "error": "Permission denied." }
        response = app.response_class(
            response=json.dumps(data),
            status=550,
            mimetype='application/json'
        )
        return response

    cursor = get_hive_cursor()

    if cursor is None:
        data = { "error": "Could not connect to Hive" }
        response = app.response_class(
            response=json.dumps(data),
            status=500,
            mimetype='application/json'
        )
        return response

    timestamp = time.time()

    message = '{0},{1},{2}'.format(-1, -1, timestamp)
    messagehub_client.send_message( message ) 

    time.sleep(70)

    cursor.execute(
            'select * from movie_ratings where rating = {0}'.format(timestamp), 
            configuration={ 
                'hive.mapred.supports.subdirectories': 'true', 
                'mapred.input.dir.recursive': 'true' 
                })
    df = as_pandas(cursor)
    count = df.shape[0]

    if count == 1:
        data = { "ok": "App rating found in hadoop." }
        response = app.response_class(
            response=json.dumps(data),
            status=200,
            mimetype='application/json'
        )
        return response
    else:
        data = { "error": "App rating not found in hadoop." }
        response = app.response_class(
            response=json.dumps(data),
            status=500,
            mimetype='application/json'
        )
        return response

ASSIGNMENT/VENKATESH/ASSIGNMENT 2 FLASK APPLICATION/web_app/app/templates/main/bi_connection_issue.html
{% extends "base.html" %}

{% block title %}BigInsights cluster unavailable.{% endblock %}

{% block page_content %}
<div class="page-header">
    <p>BigInsights cluster unavailable - please try later.</p>
</div>
{% endblock %}

ASSIGNMENT/VENKATESH/ASSIGNMENT 2 FLASK APPLICATION/web_app/app/templates/main/bi_no_records.html
{% extends "base.html" %}

{% block title %}No records found.{% endblock %}

{% block page_content %}
<div class="page-header">
    <p>No ratings found in data warehouse.</p>
    <p>Please search for and then rate some movies. Note that it may take up to one minute for ratings to appear here.</p>
</div>
{% endblock %}

ASSIGNMENT/VENKATESH/ASSIGNMENT 2 FLASK APPLICATION/web_app/app/templates/main/bi_not_enabled.html
{% extends "base.html" %}

{% block title %}BigInsights connectivity has not been configured.{% endblock %}

{% block page_content %}
<div class="page-header">
    <p>Admin functionality not available - BigInsights connectivity has not been configured.</p>
</div>
{% endblock %}

ASSIGNMENT/VENKATESH/ASSIGNMENT 2 FLASK APPLICATION/web_app/app/templates/main/embed.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block head %}
    {{ super() }}
    {{ js_resources|indent(4)|safe }}

    {{ css_resources|indent(4)|safe }}

    {{ plot_script|indent(4)|safe }}
{% endblock %}

{% block title %}Movie recommender{% endblock %}

{% block page_content %}

    <div class="page-header">
        <h2>Application Analytics</h2>
    </div>

    <div>
        <p>The ratings data for this Analytics Example chart is retrieved from Hadoop using Hive API.</p>
    </div>

    <div class="row">
        {{ plot_div|indent(4)|safe }}
    </div>

    <br/>

    <div>
        Note:
        <ul>
            <li>Every time a user rates a movie in the web application a message is put on Message Hub capturing the rating details.</li>
        <li>A backgroung spark streaming job on Hadoop ingests ratings from Message Hub using a batch window size of 60 seconds.</li>
        </ul>
        <p>Please allow time for new ratings in the web application to appear in the chart.</p>
    </div>

    <br/>

{% endblock %}

ASSIGNMENT/VENKATESH/ASSIGNMENT 2 FLASK APPLICATION/web_app/app/templates/main/home.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block title %}Movie recommender{% endblock %}

{% block page_content %}

    <h2>Overview</h2>
    <p>Welcome to this demo movie recommender application.  This demo has been installed with approximately four thousand movies and 500,000 ratings.  The ratings have been generated randomly.  The purpose of this web application is to allow users to search for movies, rate movies, and receive recommendations for movies based on their ratings.
    <p>To get started:
    <ul>
        {% if not current_user.is_authenticated %}
        <li>New users: <a href="{{ url_for('auth.register') }}">Register</a> for an account</li>
        <li>Existing users: <a href="{{ url_for('auth.login') }}">Login</a> to your account</li>
        {% endif %}
        <li>Use the Search box in the header to search for and rate some movies</li>
        <li><a href="{{ url_for('main.recommendations') }}">Get Recommendations</a> for movies</li>
        <li>Click on the <a href="/report">Analytics Dashboard</a> link in the footer to view analytics</li>
    </ul>
    <p><b>NOTE:</b> The goal of this webapp is to show Apache Spark Machine Learning. Therefore, some functionality is missing and it doesn't have the polish that you would expect from a commercial movie recommendation web site.</p>


    <h2>Technologies</h2>
    <p>The technologies used in this demo are:</p>
    <br/>

    <img alt="Overall Architecture" src="{{ url_for('static', filename='movie-recommender-demo.png') }}" width="75%">

    <br/>
    <br/>
    
    <h2>Source Code</h2>
    <p>The source code for the web application and the jupyter notebooks are available in github: <a href="https://github.com/snowch/movie-recommender-demo/">here</a></p>

    <h2>Running your own demo instance</h2>

    <p>If you would like to deploy your own instance of this demo using your own unique url, please follow the instructions in the github project.

{% endblock %}

ASSIGNMENT/VENKATESH/ASSIGNMENT 2 FLASK APPLICATION/web_app/app/templates/main/recommendations.html
{% extends "base.html" %}

{% block title %}Movie Recommendations{% endblock %}

{% block page_content %}


<div>
{% if current_user.is_authenticated %}

<div>
    <p>
        <b>
            <font color="red">
                <span class="glyphicon glyphicon-warning-sign"></span>&nbsp; Important information about the recommendations:
            </font>
        </b>
    <ul>
        <li>Below we show the predicted rating values. However, this approach is not a best practice in production applications because when users see numbers they expect all of the recommendations to be very accurate model of their movie preferences. The predicted rating values are displayed here only for demonstration purposes.</li> 
        <li>The predicated ratings are generated from a source dataset that was randomly created.  Therefore the recommendations provided here are not likely to make much sense due to the random nature of the source data.  Production recommender systems will use a large dataset of actual user ratings and will therefore provide much better recommendations.</li>
</div>

<hr>

    {% if recommendations %}


    <table class="table table-striped">
      <thead>
        <tr>
          <th>Movie ID</th>
          <th>Movie Name</th>
          <th>Predicated Rating</th>
        </tr>
      </thead>
      <tbody>
      {% for recommendation in recommendations %}
      <tr>
          <td>{{ recommendation.movie_id }}</td>
          <td>{{ recommendation.movie_name }}</td>
          <td>{{ '{0:.2f}'.format(recommendation.rating|float) }}</td>
      </tr>
      {% endfor %}
      </tbody>
    </table>

    <hr/>

<div>
    <h3>How are the recommendations created?</h3>
    <p>Recommendations are generated by Apache Spark machine learning using IBM's Data Science Experience (DSX).  The following notebook gives an overview of the algorithm.</p>
    <iframe style="width:100%; height:500px;" src="https://apsportal.ibm.com/analytics/notebooks/9a6d812f-dae5-45ba-bd24-f726aeae587b/view?access_token=c4034bc38578d451b96fc29fd49bb35370b010b1aa8b37230b5ec27b72aa7a80"></iframe>
    <br/>
    <br/>
    <p>The process for generating the recommendations is described in detail in a set of notebooks <a href="https://github.com/snowch/movie-recommender-demo/tree/master/notebooks">here</a>.  You can import the notebooks into a DSX project and step through them to get a detailed understanding of the machine learning used in this web application.
    </p>
    <p>
    The DSX job last run on: <font color="red">{{ moment(timestamp).format('MMMM Do YYYY, h:mm:ss a') }} ({{ moment(timestamp).fromNow() }})</font>.</p>
</div>

<hr/>

    {% endif %}


{% else %}
    <b><a href="{{ url_for('auth.login') }}">Login</a> to get Movie recommendations...</b>
{% endif %}
</div>



{% endblock %}

ASSIGNMENT/VENKATESH/ASSIGNMENT 2 FLASK APPLICATION/web_app/app/templates/main/search_results.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block title %}Movie recommender{% endblock %}

{% block page_content %}

{% if movies %}

    <b>Movie Search Results.</b>

    {% if current_user.is_authenticated %}
        <hr>
            Movie ratings are from <b>1</b> (worst) to <b>5</b> (best).
        <hr>
    {% endif %}

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Movie ID</th>
                <th>Name</th>
                {% if current_user.is_authenticated %}
                <th>Your Rating</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for movie in movies %}
            <tr>
                <td>{{ movie.movie_id }}</td>
                <td>{{ movie.name }}</td>
                {% if current_user.is_authenticated %}
                <td>
                    <!-- TODO: crsf protection -->
                    <select id="{{ movie.movie_id }}" data-userid="{{ current_user.get_id() }}" class="rating-selector">
                        <option value="-" {% if movie.rating == None %}selected="selected"{% endif %}>-</option>
                        <option value="1" {% if movie.rating == 1 %}selected="selected"{% endif %}>1</option>
                        <option value="2" {% if movie.rating == 2 %}selected="selected"{% endif %}>2</option>
                        <option value="3" {% if movie.rating == 3 %}selected="selected"{% endif %}>3</option>
                        <option value="4" {% if movie.rating == 4 %}selected="selected"{% endif %}>4</option>
                        <option value="5" {% if movie.rating == 5 %}selected="selected"{% endif %}>5</option>
                    </select> 
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <br>
    <br>

    {% if not current_user.is_authenticated %}
    <em><b>Note:</b></em> Album ratings are not displayed because you are not logged in. <a href="{{ url_for('auth.login') }}">Login</a> to show your ratings...
    <hr/>
    {% endif %}

{% else %}
<!-- there are no movies, so we must be on the welcome screen -->

    {% if search_string == "" %}
    <p>Empty search string - please enter a movie search string.</p>
    {% else %}
    <p>No movies found for search string: <b>{{ search_string }}</b>.</p>
    <p>Remember only ~4000 movies have been uploaded.</p>
    <p>Here are some examples:</p>
    <ul>
        <li>Toy Story</a></li>
        <li>Jumanji</li>
        <li>Grumpier Old Men</li>
    </ul>
    {% endif %}


{% endif %}

{% endblock %}

{% block scripts %}
{{ super() }}
<script type="text/javascript">

// FIXME: the approach for flashing the Saving and Saved messages is clunky
$(".rating-selector").on('change', function () {
    var movie_id = this.id;
    var user_id  = this.dataset.userid;
    var rating   = this.value;

    var select_element = this;
    $(select_element).hide()
    $(select_element).parent().append('<span class="saving-note">Saving</span>')

    $.ajax({
        url: "{{ url_for('main.set_rating') }}",
        type: "POST",
        data: JSON.stringify({
            "movie_id": movie_id, 
            "user_id":  user_id,
            "rating":   rating
        }),
        contentType: "application/json; charset=utf-8",
        dataType: "json",
        success: function(){
            $(".saving-note").remove();
            $(select_element).parent().append('<span class="saving-note">Saved</span>')

            setTimeout(function(){
                $(".saving-note").remove();
                $(select_element).show();
            }, 1000);
        }
    });
});
</script>
{% endblock %}